# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61264c4d38e2d02de943a434cb42f14f349cc92aa744ab5ec2a165636684957e493a9b3ea53581043d8dc526033655818ab05ae0f0627855a445f3d4766233a3

test:
  secret_key_base: 2be57171d7d0e12bb8fbd9c205fb39f275ce933dbc78bbeb585e6b8906499eeca155d7ba487da320e05f2ca68ccfe0275d0c37916bc109e381f4d0855b5111ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
